#!/bin/bash
#===============================================================================
#
#          FILE:  |FILENAME|
# 
#         USAGE:  ./|FILENAME| 
# 
#   DESCRIPTION:  |CURSOR|
# 
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  |AUTHOR| (|AUTHORREF|), |EMAIL|
#       COMPANY:  |COMPANY|
#       VERSION:  1.0
#       CREATED:  |DATETIME|
#      REVISION:  ---
#===============================================================================
set -e -u -x
start=`date +%s`
## Set magic variables for current file & dir
__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
__file="${__dir}/$(basename "${BASH_SOURCE[0]}")"
__base="$(basename ${__file} .sh)"

## Loging the stdout
exec > >(tee -ia "${__dir}/${__file}.log" )
exec 2>&1

## set color for messages
R='\033[0;31m'
G='\033[0;32m'
NC='\033[0m'

## Running script with sudo 
if (( $EUID != 0 )); then
    echo -e "${G}Please run script with sudo ${NC}"
    exit
fi
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
end=`date +%s`
runtime=$((end-start))
echo "Time taken = $runtime"
exit 0
